### ISSUE TITLE
Publishing on atom.io

### ISSUE THREAD

**Issue by MrSimbax** [MrSimbax/colobot-development-pack#3]
Publishing the package on atom.io would make installing and finding it a little bit easier. Should we do it?

**Comment by krzys-h** [comment]
:+1:

**Comment by MrSimbax** [comment]
Done. https://atom.io/packages/colobot-development-pack Screenshot doesn't work for some reason though :(

**Comment by krzys-h** [comment]
I assume the screenshot is a bug in the Atom website itself. Probably should be reported.

**Comment by MrSimbax** [comment]
It is already reported. https://github.com/atom/atom/issues/7819
