### ISSUE TITLE
Deprecated selector in `colobot-development-pack\styles\language-satcom.atom-text-editor.less`

### ISSUE THREAD

**Issue by 691461261** [MrSimbax/colobot-development-pack#7]
In `colobot-development-pack\styles\language-satcom.atom-text-editor.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `.source.satcom .punctuation.definition.heading` => `.syntax--source.syntax--satcom .syntax--punctuation.syntax--definition.syntax--heading`

* `.source.satcom .meta.tag` => `.syntax--source.syntax--satcom .syntax--meta.syntax--tag`

* `.source.satcom .meta.link` => `.syntax--source.syntax--satcom .syntax--meta.syntax--link`

* `.source.satcom .meta.separator` => `.syntax--source.syntax--satcom .syntax--meta.syntax--separator`

* `.source.satcom .string` => `.syntax--source.syntax--satcom .syntax--string`

* `.source.satcom .string.other.link` => `.syntax--source.syntax--satcom .syntax--string.syntax--other.syntax--link`

* `.source.satcom .keyword.token` => `.syntax--source.syntax--satcom .syntax--keyword.syntax--token`

* `.source.satcom .keyword.type` => `.syntax--source.syntax--satcom .syntax--keyword.syntax--type`

* `.source.satcom .keyword.const` => `.syntax--source.syntax--satcom .syntax--keyword.syntax--const`

* `.source.satcom .keyword.key` => `.syntax--source.syntax--satcom .syntax--keyword.syntax--key`

* `.source.satcom .constant.numeric` => `.syntax--source.syntax--satcom .syntax--constant.syntax--numeric`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by MrSimbax** [comment]
Done 683bb8954f21c1e40f8935b8f70a2e72e0134fd5
